### ISSUE TITLE
Styles not included when there is only one component.

### ISSUE THREAD

**Issue by andybluntish** [11ty/eleventy-plugin-vue#10]
After following along with the basic setup described in the [blog post](https://www.netlify.com/blog/2020/09/18/eleventy-and-vue-a-match-made-to-power-netlify.com/), everything was working great. When I setup a custom input directory in the `.eleventy.js` config (and moved the files) the component styles stopped working. The page and component rendered just fine, but only the page styles were being output from `getVueComponentCssForPage`, and styles defined in the component were missing.

I found that when I added a second component file to the `_includes` directory, the styles came back. I put some logging in `EleventyVue.js` and noticed that [`entry.imports`](https://github.com/11ty/eleventy-plugin-vue/blob/master/EleventyVue.js#L155) changed when I added the second component file, even though I wasn’t importing it into the page.

Logging `entry.imports` for my `index.vue` page:

with one file (component styles not working):
```
[ 'room-with-a-059e8199.js' ]
```

with two files (component styles are working):
```
[ 'normalize-component-d98a7a19.js', 'room-with-a.js' ]
```

It appears that the `normalize-component` file is not being created when there is only one include file component (confirmed by looking in the cache directory). Also, in the broken case, the hash is suspiciously being appended to the component file name. I’m not familiar enough with this to know what `normalize-component` really does, but from what I’ve observed it certainly seems connected.

**Comment by zachleat** [comment]
Hey @andybluntish sorry for the late reply here. I _just_ pushed 0.3.0 which fixes this (I believe)

Can you retest?

**Comment by zachleat** [comment]
I pushed a test confirming that this works in 0.3.0. Going to close for now but please reopen if you see issues!
