### ISSUE TITLE
This plugin should obey core Eleventy ignore rules for *.vue files

### ISSUE THREAD

**Issue by andybluntish** [11ty/eleventy-plugin-vue#11]
When building from the project root, `.vue` files from inside `node_modules` are included (specifically I noticed test files from eleventy-plugin-vue itself). Although nothing ends up in the output directory, the components are compiled and present in the cache directory.

This is not a problem when a custom input directory has been configured (e.g. `{ dir: { input: 'src'} }` in `.eleventy.js` config).

I discovered this while attempting to debug https://github.com/11ty/eleventy-plugin-vue/issues/10.

**Comment by zachleat** [comment]
Oh interesting yeah. I think this raises a much larger question about how this plugin should obey `.eleventyignore` and `.gitignore` rules (a la https://www.11ty.dev/docs/ignores/#ignore-template-files) and does not currently.

**Comment by zachleat** [comment]
One other thing that might be interesting is a configuration option to hardcode a per-project glob to find the vue files.

**Comment by andybluntish** [comment]
Yeah, I think respecting `.eleventyignore` and `.gitignore` would be great, and generally following the Eleventy conventions as much as possible—so adding `.vue` files works just like `.njk` or `.liquid`.

A configuration glob could be nice for advanced use cases too.

**Comment by zachleat** [comment]
This will ship with 0.6.0 and 1.0.0.

**Comment by zachleat** [comment]
* 0.6.0 is out with this.
