### ISSUE TITLE
ELEVENTY_EXPERIMENTAL=true error on Windows 10

### ISSUE THREAD

**Issue by rocketgenie** [11ty/eleventy-plugin-vue#17]
Hi,

Thanks for making 11ty!

Have a problem with this plugin if you can help...

Following these instructions:

https://www.netlify.com/blog/2020/09/18/eleventy-and-vue-a-match-made-to-power-netlify.com/

I'm getting this error when running ELEVENTY_EXPERIMENTAL=true npx @11ty/eleventy:

'ELEVENTY_EXPERIMENTAL' is not recognized as an internal or external command, operable program or batch file.

From reading around I think this is an error on Windows, but I don't know why it's occurring or how to solve it.

Any ideas?

Thanks!

**Comment by philwolstenholme** [comment]
Hi @rocketgenie , the `ELEVENTY_EXPERIMENTAL=true` is something called an environmental variable.

You might benefit from reading up on using environmental variables with Node on Windows. I don't use Windows but maybe these links might get you started:

https://stackoverflow.com/a/9250168/611568 explains that you might need to use `$env:` or `set` as a prefix before setting the environmental variable.

But, https://stackoverflow.com/a/35308102/611568 is a second answer to the question above and shows how it might be easier for you to use a Node package called [cross-env](https://www.npmjs.com/package/cross-env) to make using environmental variables easier on Windows.

**Comment by rocketgenie** [comment]
Thanks Phil, that's really helpful. I had a similar problem using a few other tools and didn't realise it was Windows related.

Will do some reading!
